FROM golang:1.15-alpine

ENV APP_ROOT=/app/golang

RUN apk add --update --no-cache redis

WORKDIR ${APP_ROOT}

COPY golang/go.mod golang/go.sum ./
RUN go mod download

COPY golang .
RUN CGO_ENABLED=0 GOOS=linux go build -o main .
